version = 1

exclude_patterns = ["js/include/*"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "2.x.x"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  plugins = ["angularjs"]
  style_guide = "airbnb"

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true